name: custom
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Use custom action
        uses: sejalxz/custom-action@main
    
